//#ifdef CEAGLE_MACROS_H
//#define CEAGLE_MACROS_H

#define DEFAULT_VERIFIER_ERROR_LABEL "SVCOMP_ERROR"
#define DEFAULT_VERIFIER_ASSUME_LABEL "SVCOMP_ASSUME_FAIL"
#define SVCOMP_INTERFACE_VERIFIER_ERROR "__VERIFIER_error"
#define SVCOMP_INTERFACE_VERIFIER_ASSUME "__VERIFIER_assume"
#define SVCOMP_INTERFACE_VERIFIER_ASSERT "__VERIFIER_assert"

//#endif
